# fly.toml app configuration file generated for dateapp on 2023-07-12T04:21:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dateapp"
primary_region = "lhr"

[build]
  image = "tantawy97/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dq9otw0qy"
  CloudinarySettings__ApiKey="261852178484167"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
