# fly.toml app configuration file generated for dateapp on 2023-07-11T08:49:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dateapp"
primary_region = "cdg"

[build]
  image = "tantawy97/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dj3wmuy3l"
  CloudinarySettings__ApiKey="895484589483755"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
